### ISSUE TITLE
Create test data files.

### ISSUE THREAD

**Issue by ArthurLai93** [jes97210/monthly-lollipops#17]
Having test data that resembles the kind of data we want the application to take in will help with testing features as we develop them.

**Comment by jes97210** [comment]
I was thinking that this would be like a "wide" table, with one row for each job id and columns with the type of stage and timestamp, but that would require some specific column titles. A "long" table makes more sense, with something like a timestamp column, a description column (for the stage), and whether the job_id is starting, done, in-progress, etc.

**Comment by jes97210** [comment]
But switching to JSON would probably be easier... know about empty, expected stages an whatever. I'd say that's a 2nd release change. Simple for 1st pass.

**Comment by jes97210** [comment]
I couldn't find a good example test data set out there, but thought maybe I could make an example version using the number of items on an order being sent out. So the grouping would be the order number, and the job id's would relate to the individual items in an order.
