### ISSUE TITLE
User provides csv file to import into the d3 graph

### ISSUE THREAD

**Issue by ArthurLai93** [jes97210/monthly-lollipops#3]
This csv will follow a format in terms of what columns are needed for monthly-lollipop to visualize into a d3 graph.

**Comment by ArthurLai93** [comment]
Importing data into d3 requires that the file be available via some web_address:port. It's weird, and annoying. If you try to load it locally, you will run into some error like this

> Fetch API cannot load file:///C:/Users/arthu/Documents/Coding/monthly-lollipops/test.csv. URL scheme must be "http" or "https" for CORS request.

My first thought was to use javascript to load the data, but I don't see any posts online doing so. Will need to look into it more.

**Comment by jes97210** [comment]
Hm I see. Can I look at your code? Or a code snippet?
Also, as part of testing you have been running like a simple python server in the directory, right? Aka: `python3 -m http.server`

**Comment by ArthurLai93** [comment]
Yes, I didn't really watch any tutorials, so just learning as I go, I've hosted the application using that command.
I'm just trying to get some testing stuff to work, and then go from there.
```
d3.csv('test.csv', function(data){
    console.log(data)
    for (let i=0; i < data.length; i++){
        console.log(data[i])
    }
});

**Comment by ArthurLai93** [comment]
Nothing is showing up right now though. So gotta fix that.

**Comment by ArthurLai93** [comment]
Ok so my problems were stemming from locally opening the index.html file locally (the url in my browser would be the local filepath).
If I enter in the url that the application is hosted on, that the filepath issue resolves itself.
My interpretation of this is that if we use this tool, we need to deploy it in order for it to work.
My initial assumption was that this was a isolated tool that can be run by just importing the tool and calling its functions.
