### ISSUE TITLE
User sees visualized graph with x axis (timestamps) and y axis (job/task identifier and group identifier)

### ISSUE THREAD

**Issue by ArthurLai93** [jes97210/monthly-lollipops#4]
User sees visualized graph with x axis (timestamps) and y axis (job/task identifier and group identifier).

**Comment by jes97210** [comment]
There is no y-axis that the user actually sees (as in, there won't be ticks or anything, job/task id will just be the y-axis).
X-axis are the time stamps, but they will be DISPLAYED as a grid of days, and labelled with months.
